### ISSUE TITLE
Cameron Fry's data isn't being written; maybe because he doesn't have a GH picture?

### ISSUE THREAD

**Issue by RobertAKARobin** [wdidc/attendance#4]
He says he does, our records just haven't been updated yet...?

**Comment by jshawl** [comment]
needs a github user id - http://api.wdidc.org/students/missing_info

**Comment by RobertAKARobin** [comment]
FUUUUU

**Comment by RobertAKARobin** [comment]
How do we get it in there? Does he need to re-auth?

**Comment by mattscilipoti** [comment]
The information was manually added to students.json(commits 82cb48d97d22e28544121ae9271ca6798a34b85a, b82254503df0c693930675d08dc3767459ca01fe).
